[tasks.install-deny]
description = "Installs cargo deny."
category = "Test"
install_crate = { crate_name = "cargo-deny", binary = "cargo-deny", test_arg = "--help" }
args = [ "deny", "--help" ]

[tasks.dependencies-deny]
description = "Runs cargo deny."
category = "Test"
workspace = false
dependencies = [
    "install-deny"
]
command = "cargo"
args = ["deny", "check"]
